# Generated by Django 4.2.8 on 2024-01-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roll_no',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
    ]
