# Generated by Django 4.2.8 on 2025-03-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='prody_points',
            field=models.IntegerField(default=0),
        ),
    ]
