# Generated by Django 4.2.8 on 2025-03-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_customuser_prody_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="team_event_mapping",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
