# Generated by Django 4.2.8 on 2023-12-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_team_registered_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_members',
            field=models.IntegerField(default=4),
        ),
    ]
