# Generated by Django 4.2.8 on 2023-12-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_contactus_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
