# Generated by Django 4.2.8 on 2024-01-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_contactus_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='image',
            field=models.ImageField(blank=True, upload_to='contactus_images/'),
        ),
    ]
