# Generated by Django 4.2.8 on 2025-03-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_contactus_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='team_type',
            field=models.CharField(choices=[('CORE', 'Core Team'), ('DESIGN', 'Design Team'), ('TECH', 'Tech Team'), ('FINANCE', 'Finance Team'), ('PR', 'PR Team')], default='CORE', max_length=10),
            preserve_default=False,
        ),
    ]
