# Generated by Django 4.2.8 on 2025-03-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_contactus_team_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='bitemoji',
            field=models.ImageField(blank=True, upload_to='contactus_images/'),
        ),
    ]
