# Generated by Django 4.2.8 on 2025-03-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_team_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='created_by',
        ),
    ]
