# Generated by Django 4.2.8 on 2025-03-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_remove_team_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='whtasapp_group',
            field=models.URLField(blank=True),
        ),
    ]
