# Generated by Django 4.2.8 on 2025-03-22 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_workshop_whtasapp_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='whtasapp_group',
            new_name='whatsapp_group',
        ),
    ]
